<InitialMenu>
    id: viewmodel

    Image:
        size_hint: 1, 1
        source: 'assets/Initial_menu.jpg'
        allow_stretch: True
        keep_ratio: False

    FloatLayout:
        id: start_menu
        MDFillRoundFlatButton:
            id: btn_enter
            text: 'PLAY NOW'
            md_bg_color: 0.5, 0.3, 1, 1
            size_hint: .3, .06
            pos_hint: {'center_x':.52, 'center_y':.15}
